[build]
  # This command installs root dependencies, then navigates to 
  # your function folder to install its specific dependencies.
  command = "npm install && cd netlify/functions/reviews && npm install"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true